version: "3"
services:
  mysql5.7.18:
    image: mysql:5.7.18
    restart: always
    volumes:
      - /Users/steven/data/Docker/soft/mysql/mysql5.7.18/data:/var/lib/mysql
      - /Users/steven/data/Docker/soft/mysql/mysql5.7.18/logs:/logs
      - /Users/steven/data/Docker/soft/mysql/mysql5.7.18/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - "webnet"
    container_name: mysql5.7.18

  nginx:
    image: nginx
    restart: always
    volumes:
      - /Users/steven/data/Project:/usr/share/nginx/html
      - /Users/steven/data/Docker/soft/nginx/conf:/etc/nginx
      - /Users/steven/data/Docker/soft/nginx/log:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "webnet"
    container_name: nginx

  php7.1.21:
    image: xtceetg/php7.1.21-fpm
    restart: always
    volumes:
      - /Users/steven/data/Project:/var/www/html
      - /Users/steven/data/Docker/soft/php/php7/conf/php/:/usr/local/etc/php
      - /Users/steven/data/Docker/soft/php/php7/conf/:/usr/local/etc
      - /Users/steven/data/Docker/soft/php/php7/log:/var/log/php
    networks:
      - "webnet"
    container_name: php7.1.21
    links:
      - mysql5.7.18:mysql5.7.18
      - redis:redis

  redis:
    image: redis:4.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - "webnet"
    container_name: php

networks:
  webnet:
    driver: bridge